library(tidyverse)
library(countrycode)
Base_limpia <- P_Data_Extract_From_World_Development_Indicators_1_ %>% mutate(region=countrycode(sourcevar = "nombre del pais", origin = "country.name", destination = "region"))
Base_limpia <- P_Data_Extract_From_World_Development_Indicators_1_ %>% mutate(region=countrycode(sourcevar = `Country Name`, origin = "country.name", destination = "region"))
Base_limpia <- Base_limpia %>% rename(nombre_del_pais= `Country Name`, codigo_del_pais= `Country Code`, variable= `Series Name`)
Base_limpia <- Base_limpia %>% mutate(nombre_pais=countrycode(sourcevar = nombre_del_pais, origin = "country.name", destination = "un.name.es"), nombre_pais= coalesce(nombre_pais, nombre_del_pais))
Base_limpia <- Base_limpia %>% mutate(region = case_match(region, "Latin America & Caribbean"   ~ "América Latina y el Caribe","North America"~ "América del Norte", "Europe & Central Asia" ~ "Europa y Asia Central","Sub-Saharan Africa" ~ "África Subsahariana","Middle East & North Africa" ~ "Oriente Medio y Norte de África","East Asia & Pacific"~ "Asia Oriental y el Pacífico", "South Asia" ~ "Asia del Sur",.default = region))
Base_limpia <- Base_limpia %>% mutate(variable= case_match(variable, "GDP growth (annual %)" ~ "Crecimiento del PIB (% anual)", "GDP per capita (current US$)" ~ "PIB per cápita (US$ actuales)","GDP per capita growth (annual %)" ~ "Crecimiento del PIB per cápita (% anual)","Multidimensional poverty headcount ratio (World Bank) (% of population)" ~ "Índice de recuento de la pobreza multidimensional (Banco Mundial) (% de la población)","Inflation, consumer prices (annual %)" ~ "Inflación, precios al consumidor (% anual)", "Life expectancy at birth, total (years)" ~ "Expectativa de vida, total (años)", "Mortality rate, infant (per 1,000 live births)" ~ "Mortalidad infantil (cada 1.000 nacimientos)", "Gini index" ~ "Indice de Gini", "Government expenditure on education, total (% of GDP)" ~ "Gasto público en educación, total (% del PIB)" ,.default = variable))
Base_limpia <- Base_limpia %>% select(-4)
Base_limpia <- Base_limpia %>% select(-1)
Base_limpia <- Base_limpia %>% relocate(nombre_pais, .before = codigo_del_pais)
Base_limpia <- Base_limpia %>% pivot_longer(cols = `2016 [YR2016]`: `2025 [YR2025]`, names_to = "anio", values_to = "valores")
Base_limpia <- Base_limpia %>% mutate(anio = str_remove(anio, " \\[YR\\d{4}\\]"))
Base_limpia <- Base_limpia %>% mutate (valores = as.numeric(valores))
Base_limpia <- Base_limpia %>% filter(!is.na(region)) %>% pivot_wider(names_from = variable ,values_from = valores)
write_csv(Base_limpia, "input/base_limpia.csv")

